Repository hoprnet/hopr-admin, pull requests merged in 2023-09, with the labels that each got.

#312 Staking Hub Landing Page
  public/assets/HOPR_Node_staking.svg
  public/assets/create-you-hopr-safe-now.svg
  public/assets/docs-icon.svg
  public/assets/gnosis-chain-logo.svg
  public/assets/hopr-node.svg
  public/assets/hopr_tokens.svg
  public/assets/payment-channels.svg
  public/assets/safe-icon2.svg
  public/assets/safe-with-shadow.svg
  public/assets/social-networks/discord.svg
  public/assets/social-networks/github.svg
  public/assets/social-networks/linkedin.svg
  public/assets/social-networks/medium.svg
  public/assets/social-networks/telegram.svg
  public/assets/social-networks/twitter.svg
  public/assets/social-networks/youtube.svg
  public/assets/staking-hub-example.svg
  public/assets/staking-landing.svg
  public/assets/telegram-icon.svg
  public/assets/the-graph-logo.svg
  public/assets/web3-private.svg
  public/assets/yellow-ellipse.svg
  src/future-hopr-lib-components/Layout/footer.jsx
  src/pages/staking-hub/landingPage.tsx
  src/router.tsx
Labels: enhancement

#318 Update whole app links and FAQ links
  src/components/Faq/node-faq.tsx
  src/components/Faq/staking-alerts.tsx
  src/components/Faq/staking-faq.tsx
  src/future-hopr-lib-components/Layout/footer.jsx
  src/pages/PrivacyNotice.tsx
  src/pages/TermsOfService.tsx
  src/pages/staking-hub/landingPage.tsx
  src/router.tsx
Labels: enhancement

#311 Buy xhopr modal
  public/assets/exchanges/ascend.svg
  public/assets/exchanges/bridge.svg
  public/assets/exchanges/cow-swap.svg
  public/assets/exchanges/ramp.svg
  src/components/Modal/staking-hub/BuyXHopr.tsx
  src/pages/staking-hub/dashboard/noNodeAdded.tsx
  src/pages/staking-hub/dashboard/staking.tsx
Labels: enhancement

#335 Create Workflow to build Hopr Admin
  .github/workflows/build-docker.yaml
  .gitignore
  Dockerfile
  README.md
Labels: devops

#338 Customise the docker tag
  .github/workflows/build-docker.yaml
Labels: devops

#320 Update Transactions styling
  config.ts
  src/pages/staking-hub/dashboard/transactions.tsx
Labels: enhancement

#340 Update set up your Dapp node onboarding
  src/pages/staking-hub/onboarding/step3/1setupYourDappNode.tsx
Labels: enhancement

#346 Update open channel modal placeholder
  src/components/Modal/node/OpenOrFundChannelModal.tsx
  src/pages/node/aliases.tsx
  src/pages/node/channelsIncoming.tsx
  src/pages/node/channelsOutgoing.tsx
  src/pages/node/peers.tsx
Labels: bug, Node Admin

#348 Fix ping modal
  src/future-hopr-lib-components/Table/table-pro.tsx
  src/pages/node/aliases.tsx
  src/pages/node/channelsIncoming.tsx
  src/pages/node/channelsOutgoing.tsx
  src/pages/node/messages.tsx
  src/pages/node/peers.tsx
Labels: enhancement

#349 Remove wxhopr node admin
  src/components/InfoBar/details.tsx
  src/pages/node/info.tsx
Labels: enhancement

#339 Move get onboarding data to redux
  src/components/ConnectSafe/index.tsx
  src/store/slices/stakingHub/actionsAsync.ts
Labels: enhancement

#366 Fix messages no longer encrypted
  src/store/slices/node/websocketMiddleware.ts
Labels: bug, Node Admin

#369 Add initial #staking hash if no hash is provided
  src/pages/staking-hub/dashboard/index.tsx
Labels: bug, Staking Hub

#374 Refactor send message modal
  src/components/Modal/node/SendMessageModal.tsx
Labels: bug

#379 Fix staking hub in drawer reload
  config.ts
  src/future-hopr-lib-components/Layout/drawer.tsx
Labels: bug

#375 Move wxHopr Allowance to staking screen and rename
  src/pages/staking-hub/dashboard/node.tsx
  src/pages/staking-hub/dashboard/staking.tsx
Labels: Staking Hub

#382 Sets ALLOW_ALL on all Channel and Token operations by default.
  src/store/slices/safe/actionsAsync.ts
Labels: enhancement

#376 Improve node not eligible message
  src/store/slices/auth/actionsAsync.ts
Labels: enhancement

#390 Fix goToStepWeShouldBeOnThunk
  src/store/slices/stakingHub/actionsAsync.ts
Labels: bug

#365 Remove logs websocket
  src/components/ConnectNode/index.tsx
  src/components/ConnectNode/modal.tsx
  src/pages/node/logs.tsx
  src/router.tsx
  src/store/slices/node/index.ts
  src/store/slices/node/initialState.ts
  src/store/slices/node/websocketMiddleware.ts
Labels: enhancement, Node Admin

#380 Add notifications for safe xdai and safe wxHopr
  src/hooks/useWatcher/balances.ts
Labels: enhancement

#395 Add peer address to open outgoing channels
  src/pages/node/aliases.tsx
  src/pages/node/peers.tsx
Labels: bug

#388 Add Toast with error info for register delegate
  src/pages/staking-hub/onboarding/step5/0addNode.tsx
Labels: bug

#397 Add withdraw NFT
  package.json
  src/abi/hoprBoostNFTAbi.ts
  src/components/ConnectSafe/index.tsx
  src/future-hopr-lib-components/Button/index.tsx
  src/future-hopr-lib-components/Cards/GrayCard.tsx
  src/future-hopr-lib-components/Select/index.tsx
  src/pages/staking-hub/dashboard/safe.tsx
  src/pages/staking-hub/onboarding/step1/0optionalNftTransfer.tsx
  src/pages/staking-hub/onboarding/step2/0fundSafe.tsx
  src/pages/staking-hub/safeWithdraw.tsx
  src/store/slices/safe/actionsAsync.ts
  src/store/slices/safe/index.ts
  src/store/slices/safe/initialState.ts
  src/store/slices/stakingHub/actionsAsync.ts
  src/utils/blockchain.ts
Labels: enhancement

#396 Add force login to node admin
  src/components/ConnectNode/modal.tsx
  src/store/slices/auth/actionsAsync.ts
  src/store/slices/auth/index.ts
  src/store/slices/auth/initialState.ts
Labels: enhancement

#424 Sidebar state to localStorage
  src/future-hopr-lib-components/Layout/index.tsx
  src/store/slices/auth/index.ts
  src/store/slices/auth/initialState.ts
  src/utils/functions.ts
  src/utils/localStorage.ts
Labels: enhancement, Node Admin, Staking Hub

#427 Add disabled prop to modals
  src/components/Modal/node/AddAliasModal.tsx
  src/components/Modal/node/OpenOrFundChannelModal.tsx
  src/components/Modal/node/PingModal.tsx
  src/components/Modal/node/SendMessageModal.tsx
  src/pages/node/aliases.tsx
Labels: Node Admin

#428 Add double click to copy pro table
  src/future-hopr-lib-components/Table/table-pro.tsx
  src/pages/node/aliases.tsx
  src/pages/node/channelsIncoming.tsx
  src/pages/node/channelsOutgoing.tsx
  src/pages/node/peers.tsx
Labels: enhancement

#360 Add Create Hopr Safe Now component to landing page
  public/assets/1create-safe.svg
  public/assets/2create-safe.svg
  public/assets/3create-safe.svg
  public/assets/4create-safe.svg
  public/assets/create-safe.svg
  public/assets/get-ready.svg
  public/assets/move-funds.svg
  src/components/CardWithAccordionSteps/index.tsx
  src/pages/staking-hub/landingPage.tsx
Labels: bug, Staking Hub

#419 Format apiEndpoint URL to add http and port if not present
  src/components/ConnectNode/modal.tsx
Labels: Node Admin

#433 Add new IN and OUT channels icon in future-hopr-lib-components
  src/future-hopr-lib-components/Icons/channelsIn.tsx
  src/future-hopr-lib-components/Icons/channelsOut.tsx
  src/router.tsx
Labels: enhancement

#368 Feedback on chain component
  package.json
  src/components/FeedbackTransaction/index.tsx
  src/components/FeedbackTransaction/loading.tsx
  src/pages/staking-hub/fundNode.tsx
  src/pages/staking-hub/onboarding/step2/0fundSafe.tsx
  src/pages/staking-hub/onboarding/step7/0fundNode.tsx
  src/pages/staking-hub/onboarding/step8/0setAllowance.tsx
  src/pages/staking-hub/safeWithdraw.tsx
  src/pages/staking-hub/stakewxHOPR.tsx
Labels: enhancement

#438 Improve addNode step of onboarding & fix MagicLink redux state
  src/components/ConnectSafe/index.tsx
  src/pages/staking-hub/onboarding/step5/0addNode.tsx
Labels: Staking Hub: Onboarding

#435 Update sendMessage modal style
  src/components/Modal/node/SendMessageModal.tsx
Labels: enhancement, Node Admin

#445 Change nginx docker version + add run command on README
  README.md
  scripts/NodeAdmin.Dockerfile
Labels: bug, documentation
